local _, WS = ...
-- Generated by the WoW Survivors Tuning bench. Loaded last; overrides defaults.
WS.Tuning = {
    constants = {},
    config = { dropChanceBomb = 0.0006, dropChanceStone = 0.0007, dropChanceHourglass = 0.0002, hourglassFreeze = 7, thornsFlat = 12, thornsDamagePct = 0.5, retributionBase = 13, retributionPerRank = 8, retributionTick = 0.3, chillSlowPerRank = 0.17 },
    familiar = {},
    weapons = {
      arcane_missiles = { damage = 15, cooldown = 0.95, speed = 349, pierce = 3, range = 666, radius = 8, rankDamageStep = 0.2, evolveDamageMult = 1.29 },
      fireball = { damage = 40, cooldown = 1.15, splash = 65, evolveDamageMult = 1.496 },
      frostbolt = { cooldown = 0.9, speed = 430, rankDamageStep = 0.2587 },
      chain_lightning = { damage = 38, cooldown = 1.4, chains = 5, range = 333, evolveDamageMult = 1.635 },
      holy_nova = { damage = 45, cooldown = 2.1, radius = 165, evolveDamageMult = 2.5, evolveCooldownMult = 0.8 },
      consecration = { evolveDamageMult = 2.188 },
      shadow_bolt = { pierce = 1, evolveDamageMult = 1.501 },
      fan_of_knives = { rankDamageStep = 0.282, evolveDamageMult = 1.1, evolveCooldownMult = 0.75 },
      whirlwind = { damage = 19, cooldown = 5.7, duration = 3 },
      multishot = { rankDamageStep = 0.2151 },
      moonfire = { evolveDamageMult = 1.188 },
      avengers_shield = { evolveDamageMult = 1.503 },
      union_astral = { damage = 28 },
      union_fel = { damage = 32 },
      union_sanctuary = { damage = 102.5, knockback = 36 },
    },
    characters = {
      mage = { perkCooldownMult = 0.88, perk = "Perk: weapon cooldowns reduced by 12%." },
      priest = { perkRegen = 8, perk = "Perk: regenerates 8 health per second." },
      rogue = { perkCrit = 0.07, perk = "Perk: +10% movement speed and +7% critical strike chance." },
      warrior = { perkArmor = 5, perkHealth = 65, perk = "Perk: +5 armor and +65 maximum health." },
      warlock = { perkDamage = 0.25, perk = "Perk: +25% weapon damage." },
      shaman = { perkLuck = 0.08, perk = "Perk: +8% luck and +8% effect area." },
      paladin = { perkArmor = 4, perkHealing = 0.15, perk = "Perk: +4 armor and +15% healing received." },
    },
    upgrades = {
      might = { v = 0.12, description = "+12% weapon damage" },
      vitality = { v = 45, description = "+45 maximum health (and heals it)" },
      armor = { v = 4, description = "+4 armor (diminishing damage reduction)" },
      luck = { v = 0.08, description = "+8% luck (better and more drops)" },
      recovery = { v = 2, description = "+2 health regenerated per second" },
      dark_bargain = { v = 0.05, description = "The horde grows: +20% spawns, +8% enemy speed. You grow too: +5% XP and gold." },
      chilling_presence = { description = "Enemies near you are slowed by cold. (17%)" },
    },
    enemies = {},
    elites = {},
    bosses = {},
    combos = {},
    blessings = {
      kings = { dmg = 0.12, hp = 75, description = "+12% damage and +75 maximum health." },
      wisdom = { xp = 0.17, description = "+17% experience from every gem." },
      elune = { area = 0.18, description = "+18% effect area on everything you cast." },
      fortune = { gold = 0.25, luck = 0.12, description = "+25% gold found and +12% luck." },
      wild = { armor = 5, regen = 1.5, description = "+5 armor, +1.5 health per second, +8% movement speed." },
      air = { cooldownMult = 0.85, description = "-15% weapon cooldowns." },
      fel = { lifesteal = 0.005, description = "Your projectiles drain life: heal for < 1% of the damage they deal." },
      ancestors = { healing = 0.6, description = "+60% healing received." },
      glass_cannon = { dmg = 0.5, description = "+50% weapon damage, but -35% maximum health. Live fast." },
      bloodthirst = { killInterval = 20, healPct = 0.04, healFlat = 12 },
      momentum = { moveHaste = 0.35 },
      arcane_overflow = { overflow = 0.04, description = "Every experience gem you gather may unleash all your weapons at once. (4%)" },
    },
    meta = {
      meta_wisdom = { v = 0.01 },
      meta_luck = { v = 0.02 },
    },
    maps = {},
    difficulties = {},
    bossArena = { ringDamage = 555, spearDamage = 888, cutterDamage = 366, chainBreak = 50 },
    arenaLoadout = {},
}

local T = WS.Tuning
local function af(t,f) if not t then return end for k,v in pairs(f) do t[k]=v end end
local function ab(s,o) if not s then return end for id,f in pairs(o) do af(s[id],f) end end
af(WS.Constants,T.constants); af(WS.Config,T.config)
if WS.Familiar then af(WS.Familiar.tuning,T.familiar) end
ab(WS.Weapons,T.weapons); ab(WS.Characters,T.characters); ab(WS.Enemies,T.enemies)
ab(WS.Elites,T.elites); ab(WS.Bosses,T.bosses); ab(WS.Upgrades,T.upgrades)
if WS.Combos then ab(WS.Combos,T.combos) end
if WS.Blessings then ab(WS.Blessings,T.blessings) end
if WS.MetaUpgrades then ab(WS.MetaUpgrades,T.meta) end
if WS.Maps then ab(WS.Maps,T.maps) end
if WS.Config.difficulties then ab(WS.Config.difficulties,T.difficulties) end
if WS.BossArena then
	af(WS.BossArena.tuning, T.bossArena)
	if T.arenaLoadout and T.arenaLoadout.weapons then WS.BossArena.loadout = T.arenaLoadout end
end
